"""
Gemini Vision Analyzer — Step 1.5
===================================

Uses Google Gemini 2.0 Flash (free tier: 15 RPM, 1000 req/day, no credit card)
to analyze the input photo and extract everything useful for identity search.

Free API key: https://aistudio.google.com → "Get API Key" → takes 30 seconds.
Add to .env:  GEMINI_API_KEY=your_key_here

What Gemini gives us that reverse image search can't:
  - Direct person identification if they're a public figure
  - Visible text in the image (conference badges, nametags, company logos,
    event banners, t-shirt text) — this is the key win for non-famous people.
    A badge saying "Anuj Sharma | Microsoft Build 2025" tells us exactly who
    to search for, even if their face has never been indexed anywhere.
  - Context clues (location, event, institution, uniform)
  - Targeted search queries generated by the model itself

Output: GeminiAnalysis dataclass with all extracted fields.
The pipeline feeds identified_name and generated_queries directly into
Option B's social profile finder, bypassing the need for reverse image search
to return results with the person's name in titles first.
"""

from __future__ import annotations

import base64
import json
import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from dotenv import load_dotenv

load_dotenv()

# Gemini REST endpoint — used directly so we don't need the SDK installed
# (avoids adding a heavy dependency; requests is already in requirements.txt)
GEMINI_API_BASE = "https://generativelanguage.googleapis.com/v1beta/models"
GEMINI_MODEL    = "gemini-flash-lite-latest"  # Free tier — lite models are faster than full flash
# Lite models have thinking capability but respond in 1-5s instead of 30-90s

# Structured prompt — instructs Gemini to return clean JSON we can parse
ANALYSIS_PROMPT = """
Analyze this photo carefully. Your job is to help identify the person in it.

Return ONLY a valid JSON object with these exact keys — no markdown, no explanation:

{
  "identified_person": "Full Name or null if unknown",
  "identification_confidence": "high | medium | low | none",
  "identification_source": "Brief reason e.g. 'public figure in training data' or 'badge text' or null",
  "visible_text": ["list", "of", "all", "text", "visible", "in", "image"],
  "person_name_from_text": "Name extracted from visible badge/nametag/caption text, or null",
  "context_clues": ["list", "of", "context", "clues", "e.g.", "company logo", "event name", "location"],
  "face_description": "Brief physical description: gender, approximate age range, hair, distinguishing features",
  "generated_queries": [
    "list of 3-5 specific Google search queries to find this person online",
    "each query should target a different platform or angle",
    "e.g. '\"Name\" site:linkedin.com', '\"Name\" github', '\"Name\" company event year'"
  ],
  "notes": "Any other relevant observations about the image"
}

Be precise. If you can read text in the image, include ALL of it in visible_text.
If there is a nametag, badge, or caption with a name, put it in person_name_from_text.
For generated_queries, make them specific and actionable — include the person's name
(from identification or visible text) in quotes where possible.
"""


@dataclass
class GeminiAnalysis:
    """Structured result from Gemini Vision analysis."""

    # Person identification
    identified_person: Optional[str] = None          # Name if Gemini recognises them
    identification_confidence: str = "none"           # high | medium | low | none
    identification_source: Optional[str] = None       # why Gemini thinks it knows

    # Text and context extracted from the image
    visible_text: list[str] = field(default_factory=list)       # ALL text in image
    person_name_from_text: Optional[str] = None                  # name from badge/caption
    context_clues: list[str] = field(default_factory=list)       # event, company, location

    # For biometric description
    face_description: Optional[str] = None

    # Ready-to-use search queries
    generated_queries: list[str] = field(default_factory=list)

    # Extra
    notes: Optional[str] = None
    raw_response: Optional[str] = None   # full Gemini text for debugging
    error: Optional[str] = None          # set if API call failed

    @property
    def best_name(self) -> Optional[str]:
        """
        Best available name for social profile lookup.
        Priority: identified_person (Gemini recognises them) > person_name_from_text
        (read from badge/caption) > None.
        """
        if self.identified_person and self.identification_confidence in ("high", "medium"):
            return self.identified_person
        return self.person_name_from_text

    @property
    def succeeded(self) -> bool:
        return self.error is None

    def to_dict(self) -> dict:
        return {
            "identified_person": self.identified_person,
            "identification_confidence": self.identification_confidence,
            "identification_source": self.identification_source,
            "visible_text": self.visible_text,
            "person_name_from_text": self.person_name_from_text,
            "context_clues": self.context_clues,
            "face_description": self.face_description,
            "generated_queries": self.generated_queries,
            "notes": self.notes,
            "error": self.error,
        }


class GeminiVisionAnalyzer:
    """
    Sends an image to Gemini 2.0 Flash and returns structured GeminiAnalysis.

    Uses the REST API directly — no SDK needed.
    Free tier: 15 requests/minute, 1000 requests/day.
    Get key: https://aistudio.google.com
    """

    def __init__(self, api_key: Optional[str] = None, model: str = GEMINI_MODEL):
        self.api_key = api_key or os.getenv("GEMINI_API_KEY", "")
        self.model   = model

    def analyze(self, image_path: str) -> GeminiAnalysis:
        """
        Analyze image and return structured GeminiAnalysis.

        Args:
            image_path: Path to local image file or public http/https URL.

        Returns:
            GeminiAnalysis with all extracted fields.
            On API failure, returns GeminiAnalysis with error set — never raises.
        """
        if not self.api_key:
            return GeminiAnalysis(error=(
                "GEMINI_API_KEY is not set. "
                "Get a free key at https://aistudio.google.com → 'Get API Key' "
                "and add GEMINI_API_KEY=your_key to your .env file."
            ))

        # Load image as base64
        try:
            mime_type, image_b64 = self._load_image(image_path)
        except Exception as e:
            return GeminiAnalysis(error=f"Failed to load image: {e}")

        # Build Gemini API request
        endpoint = f"{GEMINI_API_BASE}/{self.model}:generateContent?key={self.api_key}"
        payload = {
            "contents": [{
                "parts": [
                    {"text": ANALYSIS_PROMPT},
                    {
                        "inline_data": {
                            "mime_type": mime_type,
                            "data": image_b64,
                        }
                    },
                ]
            }],
            "generationConfig": {
                "temperature": 0.1,        # low temp = more deterministic JSON output
                "maxOutputTokens": 1024,
            },
        }

        try:
            import requests as req
            resp = req.post(endpoint, json=payload, timeout=45)  # Lite models: 1-5s typical, 45s safety margin
            resp.raise_for_status()
            data = resp.json()
        except Exception as e:
            return GeminiAnalysis(error=f"Gemini API call failed: {e}")

        # Extract text from response — handles both standard and thinking models.
        # Thinking models (gemini-3.x) return parts with optional thoughtSignature;
        # we want the part that has a "text" key.
        try:
            parts = data["candidates"][0]["content"]["parts"]
            raw_text = next(
                (p["text"] for p in parts if "text" in p),
                None,
            )
            if raw_text is None:
                raise KeyError("No text part found in response")
        except (KeyError, IndexError) as e:
            return GeminiAnalysis(
                error=f"Unexpected Gemini response structure: {e}",
                raw_response=str(data),
            )

        return self._parse_response(raw_text)

    def _load_image(self, image_path: str) -> tuple[str, str]:
        """Returns (mime_type, base64_string)."""
        import requests as req

        if image_path.startswith(("http://", "https://")):
            r = req.get(image_path, timeout=20)
            r.raise_for_status()
            image_bytes = r.content
            # Guess mime type from content-type header
            ct = r.headers.get("content-type", "image/jpeg").split(";")[0].strip()
            mime_type = ct if ct.startswith("image/") else "image/jpeg"
        else:
            path = Path(image_path).expanduser().resolve()
            image_bytes = path.read_bytes()
            suffix = path.suffix.lower()
            mime_type = {
                ".jpg": "image/jpeg",
                ".jpeg": "image/jpeg",
                ".png": "image/png",
                ".webp": "image/webp",
                ".gif": "image/gif",
            }.get(suffix, "image/jpeg")

        return mime_type, base64.b64encode(image_bytes).decode("utf-8")

    def _parse_response(self, raw_text: str) -> GeminiAnalysis:
        """Parse Gemini's JSON response into a GeminiAnalysis object."""
        # Strip markdown code fences if present
        text = raw_text.strip()
        if text.startswith("```"):
            lines = text.split("\n")
            text = "\n".join(
                line for line in lines
                if not line.strip().startswith("```")
            ).strip()

        try:
            data = json.loads(text)
        except json.JSONDecodeError:
            # Try to extract JSON object from within the text
            import re
            m = re.search(r'\{.*\}', text, re.DOTALL)
            if m:
                try:
                    data = json.loads(m.group())
                except json.JSONDecodeError:
                    return GeminiAnalysis(
                        error="Could not parse Gemini JSON response",
                        raw_response=raw_text,
                    )
            else:
                return GeminiAnalysis(
                    error="Gemini response contained no JSON",
                    raw_response=raw_text,
                )

        def _str_or_none(val) -> Optional[str]:
            if val is None or str(val).lower() in ("null", "none", ""):
                return None
            return str(val)

        def _list_of_str(val) -> list[str]:
            if not val or not isinstance(val, list):
                return []
            return [str(v) for v in val if v and str(v).lower() not in ("null", "none")]

        return GeminiAnalysis(
            identified_person      = _str_or_none(data.get("identified_person")),
            identification_confidence = str(data.get("identification_confidence", "none")).lower(),
            identification_source  = _str_or_none(data.get("identification_source")),
            visible_text           = _list_of_str(data.get("visible_text")),
            person_name_from_text  = _str_or_none(data.get("person_name_from_text")),
            context_clues          = _list_of_str(data.get("context_clues")),
            face_description       = _str_or_none(data.get("face_description")),
            generated_queries      = _list_of_str(data.get("generated_queries")),
            notes                  = _str_or_none(data.get("notes")),
            raw_response           = raw_text,
        )
